import { useMemo, useState } from 'react'

type MaterialStatus = 'MATCHED' | 'REVIEW' | 'UNMATCHED'

type Material = {
  cpse: string
  code: string
  description: string
  category: string
  material: string
  size: string
  pressure: string
  status: MaterialStatus
}

const materials: Material[] = [
  {
    cpse: 'IOCL',
    code: '10003741',
    description: 'SS304 GATE VALVE 2 IN 150 LB FLG',
    category: 'Valves',
    material: 'SS304',
    size: '2 inch',
    pressure: '150 LB',
    status: 'MATCHED',
  },
  {
    cpse: 'ONGC',
    code: 'VAL-00921',
    description: 'SS 304 GATE VALVE 50.8MM CLASS 150',
    category: 'Valves',
    material: 'SS304',
    size: '50.8 mm',
    pressure: 'Class 150',
    status: 'REVIEW',
  },
  {
    cpse: 'BPCL',
    code: 'BV-004821',
    description: 'STAINLESS STEEL GATE VALVE 2"',
    category: 'Valves',
    material: 'SS304',
    size: '2 inch',
    pressure: 'Not specified',
    status: 'REVIEW',
  },
  {
    cpse: 'NTPC',
    code: 'NT-VAL-1842',
    description: 'GATE VALVE SS 304 DN50 PN16 FLANGED',
    category: 'Valves',
    material: 'SS304',
    size: 'DN50',
    pressure: 'PN16',
    status: 'MATCHED',
  },
  {
    cpse: 'SAIL',
    code: 'SAIL-FST-0082',
    description: 'HEX BOLT M16 X 60 MM SS304',
    category: 'Fasteners',
    material: 'SS304',
    size: 'M16 × 60 mm',
    pressure: '—',
    status: 'UNMATCHED',
  },
  {
    cpse: 'BHEL',
    code: 'BH-EL-22104',
    description: 'POWER CONNECTOR 415V 32A',
    category: 'Electrical',
    material: 'Copper',
    size: '32A',
    pressure: '415 V',
    status: 'MATCHED',
  },
]

function StatusBadge({ status }: { status: MaterialStatus }) {
  const label =
    status === 'MATCHED'
      ? 'Matched'
      : status === 'REVIEW'
        ? 'Review'
        : 'Unmatched'

  return (
    <span className={`material-status material-status-${status.toLowerCase()}`}>
      {label}
    </span>
  )
}

function MaterialDetails({
  material,
  onClose,
}: {
  material: Material
  onClose: () => void
}) {
  return (
    <div className="material-detail-panel">
      <div className="material-detail-header">
        <div>
          <div className="eyebrow">MATERIAL DETAILS</div>
          <h2>{material.code}</h2>
          <p>{material.description}</p>
        </div>

        <button className="material-close-button" onClick={onClose}>
          ×
        </button>
      </div>

      <div className="material-detail-section">
        <h3>Source Information</h3>

        <div className="material-detail-grid">
          <div>
            <span>CPSE</span>
            <strong>{material.cpse}</strong>
          </div>

          <div>
            <span>Original Material Code</span>
            <strong>{material.code}</strong>
          </div>

          <div>
            <span>Category</span>
            <strong>{material.category}</strong>
          </div>

          <div>
            <span>Status</span>
            <strong>
              <StatusBadge status={material.status} />
            </strong>
          </div>
        </div>
      </div>

      <div className="material-detail-section">
        <h3>Parsed Specifications</h3>

        <div className="material-spec-list">
          <div>
            <span>Material / Grade</span>
            <strong>{material.material}</strong>
          </div>

          <div>
            <span>Size / Dimension</span>
            <strong>{material.size}</strong>
          </div>

          <div>
            <span>Pressure / Rating</span>
            <strong>{material.pressure}</strong>
          </div>
        </div>
      </div>

      <div className="material-detail-section">
        <h3>Normalization</h3>

        <div className="material-check">
          <span>✓</span>
          Unit normalization
        </div>

        <div className="material-check">
          <span>✓</span>
          Abbreviation normalization
        </div>

        <div className="material-check">
          <span>✓</span>
          Specification parsing
        </div>
      </div>

      <div className="material-detail-section">
        <h3>Matching</h3>
        <p className="material-muted">
          Candidate relationships are generated by the harmonization engine.
        </p>

        <div className="material-match-summary">
          <strong>
            {material.status === 'MATCHED'
              ? '2 candidate matches found'
              : material.status === 'REVIEW'
                ? '1 candidate requires review'
                : 'No confirmed candidate match'}
          </strong>
        </div>
      </div>
    </div>
  )
}

export default function Materials() {
  const [search, setSearch] = useState('')
  const [cpse, setCpse] = useState('All CPSEs')
  const [category, setCategory] = useState('All Categories')
  const [status, setStatus] = useState('All Statuses')
  const [selectedMaterial, setSelectedMaterial] = useState<Material | null>(
    null,
  )

  const filteredMaterials = useMemo(() => {
    const query = search.trim().toLowerCase()

    return materials.filter((material) => {
      const matchesSearch =
        !query ||
        material.code.toLowerCase().includes(query) ||
        material.description.toLowerCase().includes(query) ||
        material.cpse.toLowerCase().includes(query)

      const matchesCpse =
        cpse === 'All CPSEs' || material.cpse === cpse

      const matchesCategory =
        category === 'All Categories' || material.category === category

      const matchesStatus =
        status === 'All Statuses' ||
        material.status === status

      return (
        matchesSearch &&
        matchesCpse &&
        matchesCategory &&
        matchesStatus
      )
    })
  }, [search, cpse, category, status])

  return (
    <div className="page">
      <div className="page-header materials-page-header">
        <div>
          <div className="eyebrow">MATERIAL MASTER</div>
          <h1>Materials</h1>
          <p>
            View, inspect and prepare CPSE material records for harmonization.
          </p>
        </div>

        <button className="primary-button">
          Upload Material Data
        </button>
      </div>

      <div className="materials-summary">
        <div>
          <span>Total Records</span>
          <strong>43,301</strong>
        </div>

        <div>
          <span>CPSE Sources</span>
          <strong>6</strong>
        </div>

        <div>
          <span>Normalized</span>
          <strong>38,742</strong>
        </div>

        <div>
          <span>Pending Matching</span>
          <strong>326</strong>
        </div>
      </div>

      <div className="materials-card">
        <div className="materials-toolbar">
          <input
            className="materials-search"
            type="text"
            placeholder="Search material code, description or CPSE..."
            value={search}
            onChange={(event) => setSearch(event.target.value)}
          />

          <select value={cpse} onChange={(event) => setCpse(event.target.value)}>
            <option>All CPSEs</option>
            <option>IOCL</option>
            <option>ONGC</option>
            <option>BPCL</option>
            <option>NTPC</option>
            <option>SAIL</option>
            <option>BHEL</option>
          </select>

          <select
            value={category}
            onChange={(event) => setCategory(event.target.value)}
          >
            <option>All Categories</option>
            <option>Valves</option>
            <option>Fasteners</option>
            <option>Electrical</option>
          </select>

          <select
            value={status}
            onChange={(event) => setStatus(event.target.value)}
          >
            <option>All Statuses</option>
            <option value="MATCHED">Matched</option>
            <option value="REVIEW">Review</option>
            <option value="UNMATCHED">Unmatched</option>
          </select>
        </div>

        <div className="materials-table-wrapper">
          <table className="materials-table">
            <thead>
              <tr>
                <th>CPSE</th>
                <th>Material Code</th>
                <th>Description</th>
                <th>Category</th>
                <th>Material / Grade</th>
                <th>Size</th>
                <th>Status</th>
              </tr>
            </thead>

            <tbody>
              {filteredMaterials.map((material) => (
                <tr
                  key={`${material.cpse}-${material.code}`}
                  onClick={() => setSelectedMaterial(material)}
                >
                  <td>
                    <strong>{material.cpse}</strong>
                  </td>

                  <td>
                    <span className="material-code">
                      {material.code}
                    </span>
                  </td>

                  <td className="material-description">
                    {material.description}
                  </td>

                  <td>{material.category}</td>

                  <td>{material.material}</td>

                  <td>{material.size}</td>

                  <td>
                    <StatusBadge status={material.status} />
                  </td>
                </tr>
              ))}

              {filteredMaterials.length === 0 && (
                <tr>
                  <td colSpan={7} className="materials-empty">
                    No materials match the current filters.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>

        <div className="materials-footer">
          Showing {filteredMaterials.length} of {materials.length} demo records
        </div>
      </div>

      {selectedMaterial && (
        <div
          className="material-detail-overlay"
          onClick={() => setSelectedMaterial(null)}
        >
          <div
            className="material-detail-modal"
            onClick={(event) => event.stopPropagation()}
          >
            <MaterialDetails
              material={selectedMaterial}
              onClose={() => setSelectedMaterial(null)}
            />
          </div>
        </div>
      )}
    </div>
  )
}
